/**
 * KHATRA Industrial Machine Model Registry
 * ───────────────────────────────────────
 * Extensible registry of industrial mining & manufacturing machines for 3D/AR
 * interactive training, pre-operation checklists, hazard analysis, and adaptive
 * safety assessments.
 *
 * Each machine model contains:
 *  - id, name, category, description, modelUrl, thumbnail
 *  - components (3D position, purpose, hazard, severity, PPE, procedure, safe action, relatedDomain)
 *  - hazards (overall hazard profiles)
 *  - ppe (mandatory equipment list)
 *  - inspectionSteps (pre-shift inspection checklist)
 *  - trainingQuestions (interactive scenario-based questions for Training Mode)
 */

export const SEVERITY_COLORS = {
  HIGH: '#D93025',   // Red
  MEDIUM: '#FFB020', // Amber
  LOW: '#2E7D4F',    // Green
}

export const MACHINE_MODELS = {
  conveyor: {
    id: 'conveyor',
    name: 'Heavy Industrial Belt Conveyor',
    category: 'Material Handling & Bulk Haulage',
    description: 'Continuous bulk-material transport system used in coal and ore handling. Features rotating pulleys, drive motor, take-up units, and emergency trip-wires.',
    modelUrl: '/models/conveyor.glb',
    thumbnail: '⚙️',
    hazards: [
      'Entanglement in rotating drive drums, tail pulleys, and return idlers',
      'Contact with energized motor terminals and control gear (arc flash / shock)',
      'Belt misalignment causing frictional heat, combustible coal dust ignition, and fire',
      'High-tension mechanical energy release in counterweight tensioning systems',
    ],
    ppe: ['helmet', 'gloves', 'boots', 'goggles', 'earpro'],
    components: [
      {
        id: 'estop',
        label: 'Emergency Stop Pull-Wire & Switch',
        kind: 'component',
        position: [1.25, 0.9, 0.35],
        severity: 'HIGH',
        purpose: 'Provides instantaneous mechanical shutdown of conveyor along the entire walkway perimeter during an entanglement or roller-snag emergency.',
        hazard: 'Delayed shutdown causing catastrophic worker entrapment or continuous belt friction fire.',
        ppe: ['helmet', 'boots'],
        procedure: 'Inspect pull-wire for proper tension, freedom from obstruction, and test the micro-switch latching mechanism. Verify reset lever functions freely.',
        action: 'Never bypass or tie off emergency trip-wires. Report slack or damaged pull-wires immediately.',
        relatedDomain: 'Machinery Safety & Lockout-Tagout',
        domainSlug: 'machinery-loto',
      },
      {
        id: 'guard',
        label: 'V-Belt & Pulley Mesh Guard',
        kind: 'component',
        position: [-0.25, 1.0, 0.9],
        severity: 'HIGH',
        purpose: 'Prevents physical access to pinch points between moving conveyor belt, drive pulleys, and idlers.',
        hazard: 'In-running nip point entanglement leading to severe limb crush or amputation injuries.',
        ppe: ['helmet', 'gloves', 'boots'],
        procedure: 'Verify mesh guard is securely bolted, interlock switches are engaged, and no gaps exceed 6mm near pinch points.',
        action: 'Lockout and tag out (LOTO) all electrical feeds before removing guards for cleaning or maintenance.',
        relatedDomain: 'Machinery Safety & Lockout-Tagout',
        domainSlug: 'machinery-loto',
      },
      {
        id: 'motor',
        label: '75kW Electric Drive Motor & Gearbox',
        kind: 'component',
        position: [-1.45, 0.72, 0],
        severity: 'HIGH',
        purpose: 'Supplies mechanical torque to the head drive pulley through a high-ratio reduction gearbox.',
        hazard: 'Arc flash, electrical shock, stored mechanical torque, and surface temperatures exceeding 80°C.',
        ppe: ['helmet', 'gloves', 'boots', 'goggles', 'earpro'],
        procedure: 'Check motor casing earthing bond, look for oil leakage from gearbox seals, and verify ventilation fan cowls are unobstructed.',
        action: 'De-energize, isolate circuit breaker, test absence of voltage, and attach padlock/danger tag before touching.',
        relatedDomain: 'Electrical Hazard Response',
        domainSlug: 'electrical-hazard',
      },
      {
        id: 'roller',
        label: 'Return Idler & Snub Pulley',
        kind: 'component',
        position: [0.1, 0.45, -0.55],
        severity: 'MEDIUM',
        purpose: 'Supports the return run of the rubber belt and maintains belt wrap angle on the drive drum.',
        hazard: 'Material buildup causing belt wander, bearing seizure, frictional spark generation, and pinch injury.',
        ppe: ['helmet', 'gloves', 'boots'],
        procedure: 'Visual check for seized rollers, excessive wobble, or grooved shell wear while belt is stationary or from behind guarding.',
        action: 'Never use scrapers or hand tools to clear spillage near moving rollers; shut down and isolate before cleaning.',
        relatedDomain: 'Machinery Safety & Lockout-Tagout',
        domainSlug: 'machinery-loto',
      },
      {
        id: 'belt',
        label: 'Reinforced Rubber Conveyor Belt',
        kind: 'component',
        position: [0, 0.65, 0.8],
        severity: 'MEDIUM',
        purpose: 'Continuous load-carrying rubberized vulcanized belt that conveys mined material.',
        hazard: 'Longitudinal tears, belt slip against drive pulley producing friction smoke, and static discharge.',
        ppe: ['helmet', 'boots', 'goggles'],
        procedure: 'Inspect belt splices for edge fraying, deep gouges, and verify belt tracking alignment along carry idlers.',
        action: 'Ensure zero personnel ride on conveyor belts. Report tracking wander before belt rubs against structural steel.',
        relatedDomain: 'Fire & Explosion Response',
        domainSlug: 'fire-explosion',
      },
      {
        id: 'electrical',
        label: 'Local Control Station & Isolator',
        kind: 'component',
        position: [1.0, 0.18, -0.7],
        severity: 'HIGH',
        purpose: 'Local lockable electrical isolator and pre-start audible warning siren enclosure.',
        hazard: 'Energized conductors, water/dust ingress causing short-circuit flashover, unannounced remote restart.',
        ppe: ['gloves', 'boots', 'goggles'],
        procedure: 'Inspect enclosure door latch, verify IP65 weather seal, and confirm padlock hasps accept master safety locks.',
        action: 'Always verify isolation by attempting a local push-button start after locking out.',
        relatedDomain: 'Electrical Hazard Response',
        domainSlug: 'electrical-hazard',
      },
      {
        id: 'pneumatic',
        label: 'Pneumatic Belt Tensioner & Scraper',
        kind: 'component',
        position: [-1.1, 0.35, 0.7],
        severity: 'LOW',
        purpose: 'Maintains uniform belt tension and cleans residual fine particulate from the discharge pulley.',
        hazard: 'Pneumatic hose whip, stored pressure, and airborne fine dust projection.',
        ppe: ['helmet', 'goggles', 'gloves'],
        procedure: 'Check air pressure gauge reads 4-6 bar, inspect whip-checks on quick-disconnect hose fittings.',
        action: 'Depressurize pneumatic accumulator valve prior to servicing belt cleaner blades.',
        relatedDomain: 'Dust & Respiratory Hazard Protection',
        domainSlug: 'dust-respiratory',
      },
    ],
    inspectionSteps: [
      { id: 'cs-1', label: 'Emergency stop pull-wire is properly tensioned and unobstructed', required: true, relatedComponentId: 'estop' },
      { id: 'cs-2', label: 'Fixed drive and nip-point guards are securely bolted in position', required: true, relatedComponentId: 'guard' },
      { id: 'cs-3', label: 'Drive motor and gearbox show no lubricant leakage or overheated smell', required: true, relatedComponentId: 'motor' },
      { id: 'cs-4', label: 'Return idlers rotate freely with no coal fines accumulation', required: true, relatedComponentId: 'roller' },
      { id: 'cs-5', label: 'Electrical control enclosure is dry, closed, and earth conductor is intact', required: true, relatedComponentId: 'electrical' },
      { id: 'cs-6', label: 'Pre-start audible warning horn sounds 10 seconds prior to motion', required: true, relatedComponentId: 'estop' },
      { id: 'cs-7', label: 'All workers in area wearing mandatory PPE (helmet, gloves, safety boots, goggles)', required: true, relatedComponentId: 'belt' },
    ],
    trainingQuestions: [
      {
        id: 'tq-c1',
        componentId: 'guard',
        prompt: 'You notice a heavy accumulation of spilled ore beneath the conveyor belt guard. What is the correct safe sequence?',
        options: [
          'Reach under the guard with a long shovel while the conveyor continues operating slowly',
          'Lock out the electrical isolator, verify zero motion, tag the switch, and then clear the spillage',
          'Ask the control room operator to watch closely while you quickly scrape the tail drum',
          'Spray high-pressure water through the guard mesh to flush the debris away',
        ],
        correctIndex: 1,
        explanation: 'Under DGMS and OSHA regulations, cleaning near conveyor drums requires positive electrical isolation and LOTO. Never clear spillage from running conveyors.',
        safeAction: 'Full LOTO, release stored tension, and inspect guarding before re-energizing.',
        relatedDomain: 'Machinery Safety & Lockout-Tagout',
      },
      {
        id: 'tq-c2',
        componentId: 'estop',
        prompt: 'During pre-shift inspection, you find the emergency pull-wire is loose and dangling without tension. How should you proceed?',
        options: [
          'Tie a knot in the wire to shorten it and run the shift',
          'Operate the conveyor normally as long as the local emergency push button on the panel works',
          'Immediately tag out the conveyor as out-of-service and notify maintenance to re-tension the trip-wire',
          'Ignore it unless an emergency actually occurs',
        ],
        correctIndex: 2,
        explanation: 'A deactivated or slack emergency pull-wire is a critical safety defect. The conveyor cannot run without a functional emergency trip mechanism.',
        safeAction: 'Lockout equipment until certified maintenance re-tensions and tests the switch.',
        relatedDomain: 'Machinery Safety & Lockout-Tagout',
      },
      {
        id: 'tq-c3',
        componentId: 'motor',
        prompt: 'Before carrying out electrical inspection on the 75kW conveyor drive motor, what must be done after opening the circuit breaker?',
        options: [
          'Touch the terminals quickly with the back of your hand to check for warmth',
          'Lock the breaker, attach a Danger tag, and verify zero voltage using an approved calibrated voltage detector',
          'Turn off the room light switch and proceed immediately',
          'Wait 2 minutes for the power to drain naturally into the ground',
        ],
        correctIndex: 1,
        explanation: 'De-energization must always be accompanied by LOTO and formal verification of the absence of hazardous electrical energy.',
        safeAction: 'Lock, tag, and verify absence of voltage with a calibrated tester.',
        relatedDomain: 'Electrical Hazard Response',
      },
      {
        id: 'tq-c4',
        componentId: 'roller',
        prompt: 'A seized return roller is creating high frictional heat and squealing against the rubber belt. What is the primary catastrophic risk?',
        options: [
          'High electrical consumption by the drive unit',
          'Friction ignition of the rubber belt leading to a rapid underground mine fire',
          'Cosmetic paint discoloration on the roller shell',
          'Mild conveyor slowdown of less than 2%',
        ],
        correctIndex: 1,
        explanation: 'Friction between a seized roller and a moving belt is a notorious cause of devastating mine conveyor fires.',
        safeAction: 'Stop conveyor immediately, inspect for thermal damage, and replace seized roller.',
        relatedDomain: 'Fire & Explosion Response',
      },
    ],
  },

  'drill-rig': {
    id: 'drill-rig',
    name: 'Hydraulic Underground Mining Drill Rig',
    category: 'Rock Drilling & Roof Bolting',
    description: 'Track-mounted hydraulic drilling rig used for blast-hole drilling, rock bolting, and geotechnical sampling in underground stopes and tunnels.',
    modelUrl: '/models/drill-rig.glb',
    thumbnail: '⛏️',
    hazards: [
      'Entanglement in high-speed rotating drill steel and chuck',
      'High-pressure hydraulic fluid injection injuries (>250 bar)',
      'Uncontrolled mast movement or hydraulic hose rupture',
      'Inhalation of toxic respirable silica dust (silicosis risk)',
    ],
    ppe: ['helmet', 'gloves', 'boots', 'goggles', 'earpro', 'mask'],
    components: [
      {
        id: 'mast',
        label: 'Drill Mast & Feed Cylinder',
        kind: 'component',
        position: [0, 1.8, 0],
        severity: 'HIGH',
        purpose: 'Provides rigid structural guidance and hydraulic feed thrust for the advancing rotary-percussive rock drill.',
        hazard: 'Crush hazard between feed cradle and mast stops, structural collapse if locking pins shear.',
        ppe: ['helmet', 'boots', 'gloves'],
        procedure: 'Inspect mast locking hydraulic pins, check feed chains/ropes for strand breakage, verify mast cylinder lock valves.',
        action: 'Never enter the mast operational arc when hydraulics are pressurized.',
        relatedDomain: 'Machinery Safety & Lockout-Tagout',
        domainSlug: 'machinery-loto',
      },
      {
        id: 'head',
        label: 'High-Torque Rotary Drill Head & Chuck',
        kind: 'hazard',
        position: [0, 0.6, 1.2],
        severity: 'HIGH',
        purpose: 'Delivers hydraulic rotation torque (up to 3,000 Nm) and percussive shockwaves to fracture hard rock.',
        hazard: 'Severe rotating entanglement hazard capable of instantly catching loose clothing, hair, or limbs.',
        ppe: ['helmet', 'goggles', 'earpro', 'boots'],
        procedure: 'Check chuck threads for spalling, confirm drill steel retainer latch is fully locked.',
        action: 'Never hold or guide rotating drill steel by hand. Stand completely clear of the rotating axis.',
        relatedDomain: 'Machinery Safety & Lockout-Tagout',
        domainSlug: 'machinery-loto',
      },
      {
        id: 'hydraulic',
        label: 'High-Pressure 250-Bar Hydraulic Lines',
        kind: 'hazard',
        position: [-1.1, 0.8, 0.5],
        severity: 'HIGH',
        purpose: 'Distributes hydraulic oil at 250 bar (3,600 psi) to feed, slew, and rotation motors.',
        hazard: 'Fluid injection hazard: micro-pinhole leaks pierce skin and cause deep tissue necrosis / fatal toxicity.',
        ppe: ['gloves', 'goggles', 'helmet'],
        procedure: 'Inspect hose sleeves for blistering, cracks, or loose swivel couplings. Use cardboard or wood to check leaks, NEVER hands.',
        action: 'Never check hydraulic leaks with bare hands. Depressurize accumulator before servicing any fitting.',
        relatedDomain: 'Machinery Safety & Lockout-Tagout',
        domainSlug: 'machinery-loto',
      },
      {
        id: 'cab',
        label: 'ROPS/FOPS Protected Operator Console',
        kind: 'component',
        position: [1.0, 0.9, -0.3],
        severity: 'LOW',
        purpose: 'Provides ergonomic control levers, dead-man interlocks, and overhead rockfall protective shielding.',
        hazard: 'Impaired visibility, disabled dead-man safety controls, or cabin structural deformation.',
        ppe: ['helmet', 'earpro'],
        procedure: 'Verify all control levers spring back to neutral, check FOPS canopy bolts, clean laminated safety windscreen.',
        action: 'Operate strictly from within the protected FOPS zone; never reach out of the cabin while drilling.',
        relatedDomain: 'Machinery Safety & Lockout-Tagout',
        domainSlug: 'machinery-loto',
      },
      {
        id: 'estop',
        label: 'Master Hydraulic Emergency Stop',
        kind: 'component',
        position: [1.25, 0.55, 0.45],
        severity: 'HIGH',
        purpose: 'Immediately dumps hydraulic pressure via pilot unload valves and shuts down diesel/electric pump.',
        hazard: 'Delayed machine shutdown during mast entrapment or hose burst.',
        ppe: ['helmet'],
        procedure: 'Test trip function at the start of every shift; verify dump valve resets smoothly.',
        action: 'Confirm emergency stop is within arm’s reach of the drilling operator.',
        relatedDomain: 'Machinery Safety & Lockout-Tagout',
        domainSlug: 'machinery-loto',
      },
      {
        id: 'dust_cyclone',
        label: 'Wet Dust Scrubber & Extraction Hood',
        kind: 'component',
        position: [0.1, 0.25, 1.4],
        severity: 'MEDIUM',
        purpose: 'Suppresses and vacuums fine quartz dust generated at the collar of the drill hole.',
        hazard: 'Exposure to respirable crystalline silica (RCS) leading to irreversible silicosis and respiratory disease.',
        ppe: ['mask', 'goggles'],
        procedure: 'Check water supply pressure to flushing collar, inspect suction hose for blockages or filter puncture.',
        action: 'Never dry-drill in siliceous rock. Ensure wet mist injection is active before starting rotation.',
        relatedDomain: 'Dust & Respiratory Hazard Protection',
        domainSlug: 'dust-respiratory',
      },
    ],
    inspectionSteps: [
      { id: 'ds-1', label: 'Hydraulic hoses inspected with cardboard/wood — no leaks, abrasions, or weeping joints', required: true, relatedComponentId: 'hydraulic' },
      { id: 'ds-2', label: 'Rotary chuck and drill steel retainer latch are intact and securely engaged', required: true, relatedComponentId: 'head' },
      { id: 'ds-3', label: 'Drill mast locking pins and safety check-valves operate properly', required: true, relatedComponentId: 'mast' },
      { id: 'ds-4', label: 'Master hydraulic emergency stop dumps pressure instantly upon depression', required: true, relatedComponentId: 'estop' },
      { id: 'ds-5', label: 'Wet dust suppression system delivers required water mist to the hole collar', required: true, relatedComponentId: 'dust_cyclone' },
      { id: 'ds-6', label: 'Operator cabin FOPS/ROPS structure free of cracks, structural bends, or missing bolts', required: true, relatedComponentId: 'cab' },
    ],
    trainingQuestions: [
      {
        id: 'tq-d1',
        componentId: 'hydraulic',
        prompt: 'You suspect a high-pressure pinhole leak in a drill rig hydraulic line. How should you safely check for the leak?',
        options: [
          'Run your bare fingers along the hose to locate the spray',
          'Use a piece of cardboard or wood held at a safe distance with safety goggles and heavy gloves on',
          'Listen closely with your ear pressed near the valve block',
          'Increase hydraulic pump pressure to make the leak more obvious',
        ],
        correctIndex: 1,
        explanation: 'Hydraulic fluid at 250 bar can easily penetrate skin without immediate pain, causing deep tissue destruction and amputation. Always use cardboard or wood.',
        safeAction: 'Use cardboard or wood; never use hands. De-energize hydraulics before inspection.',
        relatedDomain: 'Machinery Safety & Lockout-Tagout',
      },
      {
        id: 'tq-d2',
        componentId: 'dust_cyclone',
        prompt: 'The drill rig’s water suppression line freezes or clogs, causing thick grey dust to billow from the collar. What is the required immediate action?',
        options: [
          'Continue drilling fast to finish the hole before dust gets worse',
          'Put on an extra paper mask and continue drilling dry',
          'Immediately halt drilling, notify the team, and restore water suppression before resuming',
          'Turn on the cabin ventilation fan and ignore the face dust',
        ],
        correctIndex: 2,
        explanation: 'Dry drilling in hard rock creates respirable crystalline silica particles that cause silicosis. Mining regulations strictly prohibit dry drilling.',
        safeAction: 'Halt drilling, clear water nozzle blockage, and confirm dust suppression before restarting.',
        relatedDomain: 'Dust & Respiratory Hazard Protection',
      },
      {
        id: 'tq-d3',
        componentId: 'head',
        prompt: 'A drill steel becomes stuck in hard rock. A trainee attempts to climb onto the feed mast to manually strike the chuck with a sledgehammer while the rig is idling. What should you do?',
        options: [
          'Hand them a heavier hammer so they can free it quicker',
          'Order an immediate stop, ensure rig engine is off, isolate hydraulics, and use approved mechanical breakout tools',
          'Watch from behind the cabin to see if it works',
          'Increase the rotation speed while they strike the steel',
        ],
        correctIndex: 1,
        explanation: 'Climbing onto an active feed mast exposes personnel to sudden rotation or crushing if the steel suddenly frees. Rig must be shut down and isolated.',
        safeAction: 'Shut down rig, isolate hydraulics, and apply approved breakout procedures.',
        relatedDomain: 'Machinery Safety & Lockout-Tagout',
      },
    ],
  },

  crusher: {
    id: 'crusher',
    name: 'Heavy Primary Jaw Crusher',
    category: 'Ore Processing & Crushing',
    description: 'Heavy reduction jaw crusher located at pit head or underground ore pass. Breaks run-of-mine ore using stationary and swinging manganese steel jaws.',
    modelUrl: '/models/crusher.glb',
    thumbnail: '🏭',
    hazards: [
      'Catastrophic crush injuries from moving toggle plates and swinging jaws',
      'High-velocity rock projectile ejection from feed hopper',
      'Extreme noise exceeding 105 dBA causing permanent acoustic trauma',
      'Massive kinetic energy stored in heavy counterweighted flywheels',
    ],
    ppe: ['helmet', 'gloves', 'boots', 'goggles', 'earpro', 'mask'],
    components: [
      {
        id: 'hopper',
        label: 'Vibrating Feed Hopper & Chute',
        kind: 'hazard',
        position: [0, 1.5, 0.7],
        severity: 'HIGH',
        purpose: 'Receives haul truck discharge or front-end loader ore and feeds it uniformly into the crushing chamber.',
        hazard: 'Rock ejection projectiles flying into walkways; personnel falling into active crushing cavity.',
        ppe: ['helmet', 'goggles', 'boots'],
        procedure: 'Verify rock deflector curtains are intact, check exclusion zone barriers, and inspect feed throat for bridging.',
        action: 'Never lean over the feed hopper while crusher is operating. Use rock breakers remotely.',
        relatedDomain: 'Machinery Safety & Lockout-Tagout',
        domainSlug: 'machinery-loto',
      },
      {
        id: 'guard',
        label: 'Flywheel & V-Belt Heavy Guarding',
        kind: 'component',
        position: [0, 0.75, 1.0],
        severity: 'HIGH',
        purpose: 'Encloses twin massive flywheels (up to 3 tonnes each) and multiple V-belts.',
        hazard: 'Massive rotational kinetic energy entanglement capable of instant fatalities.',
        ppe: ['helmet', 'gloves', 'boots'],
        procedure: 'Verify heavy steel enclosure is padlocked, hinges are lubricated, and proximity interlocks are active.',
        action: 'Never enter guard perimeter while flywheel is turning, even after motor power is disconnected.',
        relatedDomain: 'Machinery Safety & Lockout-Tagout',
        domainSlug: 'machinery-loto',
      },
      {
        id: 'motor',
        label: '132kW Slip-Ring Induction Drive Motor',
        kind: 'component',
        position: [-1.5, 0.55, 0],
        severity: 'HIGH',
        purpose: 'Provides high starting torque to rotate eccentric shaft and drive jaw toggle mechanism.',
        hazard: 'High voltage 415V/3.3kV electrical hazards, arc flash risk during start-up, and motor bearing overheating.',
        ppe: ['helmet', 'gloves', 'boots', 'goggles', 'earpro'],
        procedure: 'Check temperature gauges on stator/bearing housings, inspect motor earth bonding cables.',
        action: 'Lock out main high-voltage circuit breaker before any maintenance or belt tension adjustment.',
        relatedDomain: 'Electrical Hazard Response',
        domainSlug: 'electrical-hazard',
      },
      {
        id: 'dust',
        label: 'High-Pressure Water Mist Suppression Bar',
        kind: 'component',
        position: [0.9, 1.1, -0.2],
        severity: 'MEDIUM',
        purpose: 'Sprays pressurized atomized water droplets across the jaw mouth to suppress respirable mineral dust.',
        hazard: 'Respirable dust cloud inhalation and slip hazards from excessive wet run-off on walkways.',
        ppe: ['goggles', 'mask'],
        procedure: 'Check water pump pressure gauge reads at least 4.5 bar; inspect all 8 atomizing nozzles for spray pattern.',
        action: 'Ensure water suppression is turned on 30 seconds before starting the crusher feeder.',
        relatedDomain: 'Dust & Respiratory Hazard Protection',
        domainSlug: 'dust-respiratory',
      },
      {
        id: 'estop',
        label: 'Crusher Latching Emergency Stop Station',
        kind: 'component',
        position: [1.2, 0.55, 0.5],
        severity: 'HIGH',
        purpose: 'Triggers emergency stop contactors to disconnect main drive motor and feeder vibrator simultaneously.',
        hazard: 'Delayed equipment shutdown during a hopper bridging collapse or foreign metal uncrushable object event.',
        ppe: ['helmet'],
        procedure: 'Perform mechanical press-and-twist reset test during pre-op inspection; check trip continuity.',
        action: 'Keep a 1-meter clear radial clearance around the emergency stop button at all times.',
        relatedDomain: 'Machinery Safety & Lockout-Tagout',
        domainSlug: 'machinery-loto',
      },
      {
        id: 'platform',
        label: 'Inspection Platform, Handrails & Toe-Boards',
        kind: 'component',
        position: [0, 0.95, 1.03],
        severity: 'LOW',
        purpose: 'Allows safe elevated visual monitoring of crushing chamber without risk of falling into feed chute.',
        hazard: 'Slips, trips, falls from height, and tools dropped onto machinery below.',
        ppe: ['helmet', 'boots'],
        procedure: 'Inspect grating for loose clamps, verify 1100mm top-rail and 100mm toe-board are intact, check self-closing gate.',
        action: 'Keep platform clear of loose rocks, grease, and tools. Always secure safety harness when opening access gate.',
        relatedDomain: 'Machinery Safety & Lockout-Tagout',
        domainSlug: 'machinery-loto',
      },
    ],
    inspectionSteps: [
      { id: 'cr-1', label: 'Crushing cavity visually checked — no oversize boulders or tramp metal wedged in jaws', required: true, relatedComponentId: 'hopper' },
      { id: 'cr-2', label: 'Twin flywheel safety guards are closed, bolted, and interlock keys are secured', required: true, relatedComponentId: 'guard' },
      { id: 'cr-3', label: 'Drive motor cooling fan unobstructed and vibration sensor readings are normal', required: true, relatedComponentId: 'motor' },
      { id: 'cr-4', label: 'Water mist suppression nozzles deliver full fan spray across jaw mouth', required: true, relatedComponentId: 'dust' },
      { id: 'cr-5', label: 'Emergency stop buttons on platform and ground level operate correctly', required: true, relatedComponentId: 'estop' },
      { id: 'cr-6', label: 'Hearing protection (ear defenders + ear plugs) and respiratory protection worn', required: true, relatedComponentId: 'dust' },
    ],
    trainingQuestions: [
      {
        id: 'tq-cr1',
        componentId: 'hopper',
        prompt: 'An oversize 1.5-meter granite boulder wedges across the crusher feed mouth, bridging the jaw. What is the approved safe method to clear it?',
        options: [
          'Climb into the hopper with a crowbar to pry the rock loose while the crusher continues idling',
          'Throw a small explosive charge into the hopper while standing on the catwalk',
          'Stop feeder, isolate crusher, lock out, and use an overhead hydraulic rock breaker operated from the control cabin',
          'Drop another heavy boulder on top of it to smash it through the jaws',
        ],
        correctIndex: 2,
        explanation: 'Personnel must never enter an active crushing chamber. Clearing bridged rock requires full isolation and remote hydraulic rock-breaker equipment.',
        safeAction: 'Stop equipment, LOTO, and deploy remote hydraulic rock breaker.',
        relatedDomain: 'Machinery Safety & Lockout-Tagout',
      },
      {
        id: 'tq-cr2',
        componentId: 'guard',
        prompt: 'The main crusher motor power is turned off at the isolator. Can a technician immediately open the flywheel guard to inspect the belts?',
        options: [
          'Yes, because electrical power is disconnected',
          'No, because the massive 3-tonne flywheels have high rotational inertia and take several minutes to come to a complete standstill',
          'Yes, as long as they wear cut-resistant gloves',
          'Only if another worker holds the flywheel by hand',
        ],
        correctIndex: 1,
        explanation: 'Stored kinetic mechanical energy is fatal. Operators must wait for zero rotational motion before opening flywheel guards.',
        safeAction: 'Wait for complete zero-energy standstill and lock out before opening guards.',
        relatedDomain: 'Machinery Safety & Lockout-Tagout',
      },
    ],
  },

  excavator: {
    id: 'excavator',
    name: 'Open-Pit Mining Hydraulic Excavator',
    category: 'Heavy Earthmoving & Loading',
    description: 'Heavy crawler hydraulic shovel/excavator used for overburden stripping and haul-truck loading in open-pit mining operations.',
    modelUrl: '/models/excavator.glb',
    thumbnail: '🚜',
    hazards: [
      'Blind spot pedestrian strikes within the 360-degree swing radius',
      'Structural boom collapse or cylinder rupture under severe load',
      'Electrocution from contact with overhead powerlines during loading',
      'High-pressure hydraulic hose burst (>350 bar) in engine compartment',
    ],
    ppe: ['helmet', 'vest', 'boots', 'goggles', 'earpro', 'gloves'],
    components: [
      {
        id: 'boom',
        label: 'Reinforced Box-Section Boom & Cylinders',
        kind: 'component',
        position: [0, 1.8, 1.5],
        severity: 'MEDIUM',
        purpose: 'Provides lifting force and articulation for digging and loading 40-tonne payloads into haul trucks.',
        hazard: 'Crush zone beneath suspended load, hydraulic hose rupture causing rapid boom descent.',
        ppe: ['helmet', 'boots', 'vest'],
        procedure: 'Check boom pivot pins for grease leakage, inspect cylinder rod chrome for scoring, check safety check-valves.',
        action: 'Never stand or walk under a raised boom or bucket, whether machine is active or parked.',
        relatedDomain: 'Machinery Safety & Lockout-Tagout',
        domainSlug: 'machinery-loto',
      },
      {
        id: 'bucket',
        label: '12m³ Heavy-Duty Rock Bucket & Teeth',
        kind: 'hazard',
        position: [0, 0.4, 2.8],
        severity: 'HIGH',
        purpose: 'Directly penetrates and scoops blasted hard rock into 100-tonne haul trucks.',
        hazard: 'Falling rock spillages, detached bucket teeth flying into tires, and pin shear pinch points.',
        ppe: ['helmet', 'boots', 'goggles'],
        procedure: 'Inspect wear teeth locking pins, check side-cutters for cracks, verify bucket curl cylinder linkage.',
        action: 'Lower bucket firmly onto ground before leaving cab or performing pre-op walkaround.',
        relatedDomain: 'Machinery Safety & Lockout-Tagout',
        domainSlug: 'machinery-loto',
      },
      {
        id: 'turret',
        label: '360° Continuous Slewing Turret & Ring',
        kind: 'hazard',
        position: [0, 0.9, 0],
        severity: 'HIGH',
        purpose: 'Rotates the entire upper structure, cab, engine, and boom continuously around the crawler base.',
        hazard: 'Severe counterweight pinch point between rotating turret and stationary tracks or highwall.',
        ppe: ['helmet', 'vest', 'boots'],
        procedure: 'Check slew ring gear grease level, verify automatic swing alarm and revolving amber beacons.',
        action: 'Maintain strict 10-meter exclusion zone around counterweight swing radius at all times.',
        relatedDomain: 'Machinery Safety & Lockout-Tagout',
        domainSlug: 'machinery-loto',
      },
      {
        id: 'cab',
        label: 'Pressurized Operator Cab with Blind-Spot Cameras',
        kind: 'component',
        position: [1.1, 1.4, 0.4],
        severity: 'LOW',
        purpose: 'Houses operator controls, HVAC filtration, 360-degree camera monitors, and roll-over protection.',
        hazard: 'Operator fatigue, blind-spots obscuring small support vehicles, and disabled safety interlocks.',
        ppe: ['helmet', 'earpro'],
        procedure: 'Check all 4 external camera feeds, test horn, test windscreen wiper/washer, confirm seatbelt locks.',
        action: 'Always make eye contact or two-way radio confirmation before allowing personnel into digging zone.',
        relatedDomain: 'Machinery Safety & Lockout-Tagout',
        domainSlug: 'machinery-loto',
      },
      {
        id: 'battery_isolator',
        label: 'Master Battery & Emergency Engine Isolator',
        kind: 'component',
        position: [-1.2, 0.6, -1.1],
        severity: 'HIGH',
        purpose: 'Isolates 24V starter battery circuits and cuts fuel injection to extinguish diesel engine immediately.',
        hazard: 'Diesel fire in engine bay, battery explosion, or unexpected engine crank during inspection.',
        ppe: ['gloves', 'boots'],
        procedure: 'Verify lockable red isolator handle rotates smoothly and cuts all electrical auxiliary power.',
        action: 'Lock out battery isolator when performing daily fluid level or fan belt checks.',
        relatedDomain: 'Electrical Hazard Response',
        domainSlug: 'electrical-hazard',
      },
      {
        id: 'tracks',
        label: 'Heavy Crawler Undercarriage & Tensioner',
        kind: 'component',
        position: [-1.3, -0.2, 0],
        severity: 'MEDIUM',
        purpose: 'Distributes 100+ tonnes of ground pressure across twin crawler tracks on rocky pit benches.',
        hazard: 'Track shoe fracture, unstable bench edge collapse, and track tension grease cylinder rupture.',
        ppe: ['helmet', 'boots'],
        procedure: 'Inspect track sag (should be 40-50mm), verify track pad bolts are tight, check rollers for leaks.',
        action: 'Never position tracks parallel to a highwall or bench crest when digging.',
        relatedDomain: 'Machinery Safety & Lockout-Tagout',
        domainSlug: 'machinery-loto',
      },
    ],
    inspectionSteps: [
      { id: 'ex-1', label: 'Bucket lowered to the ground before walkaround inspection commences', required: true, relatedComponentId: 'bucket' },
      { id: 'ex-2', label: 'Swing radius (10 meters) clear of all personnel, light vehicles, and obstacles', required: true, relatedComponentId: 'turret' },
      { id: 'ex-3', label: '360-degree blind spot cameras and travel alarm verified operational in cab', required: true, relatedComponentId: 'cab' },
      { id: 'ex-4', label: 'Boom, stick, and bucket hydraulic cylinders free of oil weeping or chrome pitting', required: true, relatedComponentId: 'boom' },
      { id: 'ex-5', label: 'Engine compartment fire suppression pressure gauge in green zone; battery isolator tested', required: true, relatedComponentId: 'battery_isolator' },
      { id: 'ex-6', label: 'High-visibility safety vest, hard hat, and steel-toe boots worn by all bench personnel', required: true, relatedComponentId: 'turret' },
    ],
    trainingQuestions: [
      {
        id: 'tq-ex1',
        componentId: 'turret',
        prompt: 'A grade worker on foot approaches the excavator to speak with the operator while the machine is actively swinging. What is the major safety violation?',
        options: [
          'The worker did not wave both hands in the air',
          'The worker entered the blind-spot counterweight swing radius without two-way radio confirmation and positive operator eye contact',
          'The worker is walking too slowly across the pit bench',
          'The worker should have climbed onto the crawler tracks while it was turning',
        ],
        correctIndex: 1,
        explanation: 'Counterweight swing radius blind-spots are a leading cause of fatalities in open-pit mining. Personnel must stay 10m away until operator stops machine, lowers bucket, and signals.',
        safeAction: 'Maintain 10m exclusion zone; establish radio contact before approaching.',
        relatedDomain: 'Machinery Safety & Lockout-Tagout',
      },
      {
        id: 'tq-ex2',
        componentId: 'boom',
        prompt: 'The excavator is loading blasted rock on an elevated bench where an overhead 11kV electrical cable is suspended. What minimum clearance distance must be maintained?',
        options: [
          '50 centimeters is plenty as long as it does not physically touch',
          'At least 3 meters (or site-specified HV exclusion zone, often 5-10m) from any part of the boom, bucket, or antennae',
          'Clearance is only required when it rains',
          'No clearance needed because the rubber tracks insulate the excavator',
        ],
        correctIndex: 1,
        explanation: 'High voltage electricity can arc across air gaps to metal booms. Steel crawler tracks do NOT insulate high voltage. Strict minimum approach distances must be enforced.',
        safeAction: 'Maintain minimum 3m (or site rule 5m+) clearance from overhead HV power lines.',
        relatedDomain: 'Electrical Hazard Response',
      },
    ],
  },
}

export const MACHINE_MODEL_LIST = Object.values(MACHINE_MODELS)

export function getMachineModel(id) {
  return MACHINE_MODELS[id] || MACHINE_MODELS.conveyor
}

export function createCustomMachineModel(customData) {
  if (!customData) return MACHINE_MODELS.conveyor
  const id = customData.model_id || customData.id || 'custom-model'
  const name = customData.name || customData.machine_id || 'Custom 3D Machine'
  return {
    id,
    name,
    category: 'Custom Generated / Uploaded Asset',
    description: customData.prompt || 'Custom industrial machine 3D asset generated via Text-to-3D pipeline or uploaded.',
    modelUrl: customData.model_url,
    thumbnail: '✨',
    hazards: [
      'Moving machinery and rotating parts hazard',
      'High-pressure or electrical energy isolation required prior to maintenance',
      'Pinch point and entrapment potential during operation',
    ],
    ppe: ['helmet', 'gloves', 'boots', 'goggles'],
    components: [
      {
        id: 'cust-comp-1',
        label: 'Primary Operating Assembly',
        kind: 'component',
        position: [0, 0.8, 0],
        severity: 'MEDIUM',
        purpose: 'Main functional unit of the generated equipment model.',
        hazard: 'Mechanical pinch point and moving parts.',
        ppe: ['helmet', 'gloves', 'boots'],
        procedure: 'Verify guarding integrity, inspect mechanical connections, and check for loose hardware.',
        action: 'Lockout and tag out (LOTO) before inspecting internal mechanisms.',
        relatedDomain: 'Machinery Safety & Lockout-Tagout',
        domainSlug: 'machinery-loto',
      },
      {
        id: 'cust-comp-2',
        label: 'Emergency Isolation Point',
        kind: 'component',
        position: [0.8, 0.5, 0.4],
        severity: 'HIGH',
        purpose: 'Provides emergency stoppage and energy isolation.',
        hazard: 'Delayed shutdown during an entanglement emergency.',
        ppe: ['helmet', 'boots'],
        procedure: 'Test emergency shutdown actuator and ensure clear, unobstructed access.',
        action: 'Never obstruct or bypass emergency trip points.',
        relatedDomain: 'Machinery Safety & Lockout-Tagout',
        domainSlug: 'machinery-loto',
      },
    ],
    inspectionSteps: [
      { id: 'c-1', label: 'Surrounding work area clear of debris and trip hazards', required: true, relatedComponentId: 'cust-comp-1' },
      { id: 'c-2', label: 'Emergency isolation and shutdown control accessible and undamaged', required: true, relatedComponentId: 'cust-comp-2' },
      { id: 'c-3', label: 'Appropriate PPE donned (Hard hat, gloves, steel-cap boots, eye protection)', required: true, relatedComponentId: 'cust-comp-1' },
    ],
    trainingQuestions: [
      {
        id: 'tq-cust-1',
        componentId: 'cust-comp-2',
        prompt: 'Before performing any walkaround inspection or maintenance on this machine, what must be confirmed?',
        options: [
          'No check is required if the machine sounds quiet',
          'Lockout-Tagout (LOTO) isolation is verified and zero-energy state is confirmed',
          'Only that you are wearing safety glasses',
          'Ask a coworker to watch the switch while you work',
        ],
        correctIndex: 1,
        explanation: 'Isolation and zero-energy state verification (LOTO) is mandatory before approaching hazardous mechanical components.',
        safeAction: 'Verify LOTO before commencing inspection.',
        relatedDomain: 'Machinery Safety & Lockout-Tagout',
      },
    ],
  }
}
